jflex-de/jflex

- jflex/pom.xml
- pom.xml
Cup 11b now requires JDK 6 to compile.
Since we now use cub 11b (see #175), bump our prerequesite from Jdk 5 to jdk 6.
> Bump JDK to version 6.

- jflex-maven-plugin/pom.xml
- jflex-maven-plugin/src/main/java/de/jflex/plugin/maven/JFlexMojo.java
- jflex-unicode-maven-plugin/pom.xml
- pom.xml
- testsuite/jflex-testsuite-maven-plugin/pom.xml
Updated to maven-plugin-api 3.0.5 and introduced Mojo annotations. Marked JFlexMojo as thread-safe. Closes #211
> Marked plugin as thread safe

- .travis.yml
Travis doesn't support oracle JDK anymore. See https://github.com/travis-ci/travis-ci/issues/7884
Use openjdk7 instead of oraclejdk7.
Fix #220
> Configure Travis to use openjdk

- jflex-unicode-maven-plugin/src/main/java/jflex/DerivedAgeScanner.java
- jflex-unicode-maven-plugin/src/main/java/jflex/JFlexUnicodeMojo.java
- jflex-unicode-maven-plugin/src/main/java/jflex/NamedRange.java
- jflex-unicode-maven-plugin/src/main/java/jflex/UnicodePropertiesSkeleton.java
- testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/CustomClassLoader.java
- testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/DiffStream.java
- Performance: Inefficient map iterator
Improve loops on maps by reading the entry, rather than the key and then the value
- Use AutoClosable
- Performance: Use Integer.valueOf() instead of creating new Integer objects
```
mvn clean
mvn -N install
mvn package findbugs:findbugs
```
> Fix FindBugs issues

- pom.xml
Note that FallThrough violations have been reduced to warnings.
issue #222
> Add google error-prone in compile step.

- .travis.yml
- run-tests
Travis starts builds in a new container and already compiles everything from scratch.
There is no need to `mvn clean`.
However, if the `$TRAVIS` environment variable is not defined, the script will mimic everything Travis does by default.
> Improve run-tests.sh

- jflex/build.xml
The central.maven.org has been replaced by repo.maven.apache.org
> Update address of central Maven repo in ant script

- jflex/examples/cup/Makefile
- jflex/examples/interpreter/Makefile
- jflex/examples/java/Makefile
- run-tests
`set -e`: Exit immediately if a command exits with a non-zero status.
However
> the shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test in an if statement, **part of any command executed in a && or ||** list except the command following the final && or ||, any command in a pipeline but the last, or if the command’s return status is being inverted with !. 
https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
Hence ending the execution of the test with `&& cd ..` prevents the exit of the script in case of failure.
Change to parent directory on its own line.
Fix #242
> Let Travis fail if a test fail

- jflex-unicode-maven-plugin/pom.xml
- jflex-unicode-maven-plugin/src/main/java/jflex/JFlexUnicodeMojo.java
Use java annotations rather than javadoc (invalid) at-clauses.
> Code cleanup in jflex-unicode-maven-plugin

- .travis.yml
- scripts/run-tests.sh
* Support path with space
Use absolute MVN path wwrapped in `""` to support directory names with space.
* Speed up the build
Also, speed up the build by telling Travis to not install dependencies. Maven already does it automatically. 
* Make build logs more synthetic
- Make the build quiet when running on Travis (this strips all the "Downloading..." lines in the log).   
This also strips other build info and warnings.
Errors are still in the logs, of course.
- When executed locally, the Maven logs are still verbose
> run-tests: Support path with space

- pom.xml
- fmt plugin has nothing to do in error-prone
- disabling doclint can be made in an easier way
- disabling doclint onlyon CI server
> Simplify profiles

- docs/md/example.md
I'm not 100% sure of this fix, I was just reading and skimming the documentation, and second line in the change referenced the "next backslash", I didn't understand why the rule would work that way. Looking at the example on line 98 however makes sense, so I believe these should be the same.
> Fixed discrepancy in documentation

- cup/pom.xml
- pom.xml
That's the only supported version for Maven 3
https://maven.apache.org/plugins/maven-site-plugin/maven-3.html
Also revert  "Update maven-project-info-reports-plugin to version 3.0.0 (commit 39f4e04) which had no effect.
Fix #280
> Use maven-project-info-reports-plugin 2.2

- .travis.yml
This will
- make the build more reliale – sometimes, Travis fails to download artefacts
- make the build faster
NB There is one cache per cell in the build matrix (for jdk / env) and per branch
> Cache the .m2/repository

- .travis.yml
- jflex/build.xml
- scripts/clean.sh
- scripts/run-tests.sh
- scripts/test-unit.sh
Roll forward commit 2c10923e17b401d37a0224c2aa43855f0596cc36 (#296)
For some reason `mvn install` now fails to install `cup` and `cup_runtime`. Update the script to install those explicitly first.
> Cache .m2/repository [roll forward]

- jflex/examples/cup-maven/pom.xml
- jflex/examples/simple-maven/pom.xml
- jflex/examples/standalone-maven/pom.xml
Fixes [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
See #164
> Use UTF-8 encoding in example projects

- jflex/examples/simple-maven/src/test/resources/output.good
- jflex/src/main/java/jflex/Emitter.java
- testsuite/testcases/src/test/cases/bol/bol-0.output
- testsuite/testcases/src/test/cases/simple/simple-0.output
The main method of %debug scanners will now report the value of yychar for
each match. As opposed to yyline and yycolumn counting who report yyline+1 and
yycolumn+1, the yychar reporting starts at 0, because it is more likely to be
useful as an index into a buffer (whereas line and column are more likely to
be useful in an editor).
Fixes issue #207.
> add yychar reporting when both %debug and %char are present

- .gitignore
- .travis.yml
- scripts/deploy-source-code.sh
- scripts/test-unit.sh
We now have a branch [aggregated-java-sources](https://github.com/jflex-de/jflex/tree/aggregated-java-sources).
With this change, Travis will push the java sources of jflex (incl. generated-sources) on every commit on **master**.
> Let Travis update the aggregated-java-sources branch

- mvn-deploy.sh
- Prefer `mvnw` over `mvn`
- Also build the javadoc and source jars before deploy. Fix #315
> Use Maven wrapper in deploy script

- .travis.yml
- scripts/deploy-source-code.sh
* typo: s/desploy/deploy
Somehow, Travis doesn't fail if a script doesn't exits...
* Also add logging in deploy-source-code.sh
> Fix typo when calling deploy-source-code.sh

- pom.xml
Hopefully, this will fix Travis
```
[INFO] <<< maven-javadoc-plugin:2.10.1:test-javadoc < generate-test-sources @ jflex-maven-plugin <<<
...
[ERROR] Unable to determine if resource aopalliance:aopalliance:jar:1.0:compile exists in https://repository.apache.org/releases/
```
> Update maven-project-info-reports-plugin to version 3.0.0

- jflex/bin/jflex.bat
Use `%*` for remaining args, instead of `%1` `%2` `%3` ... `%9`
(which might me a couple)
> Minor: Udpate Windows batch script

- scripts/deploy-source-code.sh
Fix:
[aggregated-java-sources 5915c76] Update from target/jflex-parent-1.7.0-sources.jar
49 files changed, 305 insertions(+), 256 deletions(-)
Push to https://github.com/jflex-de/jflex/tree/aggregated-java-sources
commit 5915c766e5ff4352013bd1f618a337e2f006e6b3
Author: Travis CI User <travis@example.org>
Date:   Fri Sep 21 08:52:30 2018 +0000
Update from target/jflex-parent-1.7.0-sources.jar
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/jflex-de/jflex.git/'
Script failed with status 128
> Deploy script must do git config to set Travis identity

- scripts/deploy-source-code.sh
The commit fails because Travis fails to authenticate over https.
commit 2badfd11fa1f8d9ca79ec12f21609e9ec3d00b1a
Author: Travis CI <deploy@travis-ci.org>
Date:   Fri Sep 21 10:11:55 2018 +0000
Update from target/jflex-parent-1.7.0-sources.jar
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/jflex-de/jflex.git/'
Script failed with status 128
failed to deploy
> Use ssh to clone the repository

- .travis.yml
This script doesn't work on Travis because
Push to https://github.com/jflex-de/jflex/tree/aggregated-java-sources
commit 03692fce9a2385a54ae3b95435811e057881056b
Author: Travis CI User travis@example.org
Date: Fri Sep 21 09:36:07 2018 +0000
Update from target/jflex-parent-1.7.0-sources.jar
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/jflex-de/jflex.git/'
Script failed with status 128
> Temporarily Dont deploy aggregated-java-sources

- .travis.yml
- scripts/deploy-source-code.sh
The `deploy-source.sh` script doesn't work on Travis because
Push to https://github.com/jflex-de/jflex/tree/aggregated-java-sources
commit 03692fce9a2385a54ae3b95435811e057881056b
Author: Travis CI User travis@example.org
Date: Fri Sep 21 09:36:07 2018 +0000
Update from target/jflex-parent-1.7.0-sources.jar
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/jflex-de/jflex.git/'
Script failed with status 128
> Use git clone on https with existing GITHUB_TOKEN

- scripts/deploy-source-code.sh
Travis fails with 
```
Git status
On branch aggregated-java-sources
Your branch is up to date with 'origin/aggregated-java-sources'.
nothing to commit, working tree clean
On branch aggregated-java-sources
Your branch is up to date with 'origin/aggregated-java-sources'.
nothing to commit, working tree clean
Script failed with status 1
failed to deploy
```
> Don't commit on a clean working tree for aggregated-java-sources

- LICENSE.md
- scripts/deploy-source-code.sh
Since we redistribute the CUP runtime, I think we should show the CUP license in the LICENSE flle.
> Add CUP license in aggregate-java-sources

- .gitignore
I have an experimental branch to build with bazel. https://github.com/regisd/jflex/tree/bazel
Ignore these build directories.
> git:ignore bazel-*

- jflex/examples/zero-reader/Makefile
`diff` should ignore different EOL when diffing the expected result (LF) against the produced result with potentially different EOL (e.g. CRLF on Windows).
> expl zeroreader: diff ignoring different EOL

- jflex/bin/jflex.bat
Allow to define `JFLEX_HOME` and `JFLEX_VERSION` as environment variables.
Also, plus quote path to jar file.
> jflex.bat: JFLEX vars definable in cmd shell

- scripts/deploy-source-code.sh
In #361, the initial commit message was added in the commit of the aggregate-java-sources.
Unfortunately `\n` is copied verbatim.
Use multiple `--message` args instead.
From the doc:
> -m <msg>
> --message=<msg>
> Use the given <msg> as the commit message. If multiple -m options are given, their values are concatenated as separate paragraphs.
> Fix git commit --message for aggregate-java-sources

- .travis.yml
- scripts/run-ant.sh
- scripts/run-tests.sh
We have useless matrix expansion (e.g. java-format un JDK8 and java-format in JDK9).
Instead of expanding all possible values, explicitely define the inclusion we want.
> Travis: drastically reduce the build matrix.

- scripts/bazel.sh
Wrong syntax
```
if [[ -z"$CI" ]]
```
is always true
> Minor: fix shutdown condition in scritpts/bazel.sh

- pom.xml
- src/main/resources/google_checks.xml
I'm experimenting with a few third-party code quality / static analysis platforms:
- https://app.codacy.com/project/regisd/jflex
- https://codeclimate.com/github/regisd/jflex
- https://www.codefactor.io/repository/github/jflex-de/jflex
- https://ebertapp.io/github/regisd/jflex
- https://lgtm.com/projects/g/jflex-de/jflex/
They support:
- showing code coverage [with jacoco reports]
- detecting code style violations [with checkstyle]
> Add Code quality reports

- cup-maven-plugin/src/main/java/de/jflex/plugin/cup/GenerateMojo.java
- jflex-unicode-maven-plugin/src/main/java/jflex/DataFileType.java
- jflex/src/main/java/jflex/IntCharSet.java
- jflex/src/main/java/jflex/Interval.java
- jflex/src/main/java/jflex/Main.java
- jflex/src/main/java/jflex/Skeleton.java
- jflex/src/main/java/jflex/StateSet.java
- testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/CustomClassLoader.java
- testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/TestCase.java
From https://lgtm.com/projects/g/jflex-de/jflex/alerts/
- Class Interval overrides equals but not hashCode.
- Class IntCharSet overrides equals but not hashCode.
- StateSet: equals() method does not seem to check argument type.
- Main: array access might be out of bounds, as the index might be equal to the array length.
- Main: This FileInputStream is not always closed on method exit.
- Skeleton: This FileReader is not always closed on method exit.
- Skeleton: The FileInputStream and FileOutputStream classes contains a finalizer method which will cause garbage collection pauses. See JDK-8080225 for details.
> Fix PMD violations

- cup/cup/pom.xml
- cup/pom.xml
This should make sure #390 doesn't happen. Unfortunately this duplicates some info from jflex-parent, but we probably don't want cup-parent to depend on jflex-parent.
> deploy cup_runtime and cup-parent

- .travis.yml
The deploy phase didn't trigger for the past few days. Missing:
- commit a9406b60ddf66ec63a9330d9a54547cb02e5e67c (bump maven deps)
- commit 47ffc864b8979dc5c62496b3fa92a55de11ac743 (add jacoco)
- commit b4ecdc5de3e34416fcd79c39b8173e18d6178f07 (shashify "source:" in header)
- commit dedd07459972571d51665a6ac0d4a5cecb54f01f (fix lgtm code warnings)
- commit f4b8ac11abc2f55f8280b42d4ba70c270ddae52f (replace `<code>` by `{@code }`)
> Fix Aggregated java sources

- jflex-maven-plugin/pom.xml
- jflex-maven-plugin/src/main/java/de/jflex/plugin/maven/ClassInfo.java
- jflex-maven-plugin/src/main/java/de/jflex/plugin/maven/JFlexMojo.java
- jflex-maven-plugin/src/main/java/de/jflex/plugin/maven/LexSimpleAnalyzer.java
- jflex-maven-plugin/src/test/java/de/jflex/plugin/maven/ClassInfoTest.java
- jflex-maven-plugin/src/test/java/de/jflex/plugin/maven/LexSimpleAnalyzerTest.java
- pom.xml
Fix #104
Also, make ClassInfo immutable.
> Don't infer package name from lex rule names.

- README.md
Link to https://github.com/jflex-de/jflex/wiki/Build-tool-integration
> README.md: Add link to "Build tool integration"

- .travis.yml
After the split of the build matrix, `TEST_SUITE` is not defined anymore.
It's only remaining usage is to condition the deployment. `PUBLISH_SOURCES` is a more meaningful name.
> Rename TEST_SUITE=unit to PUBLISH_SOURCES=true

- cup/BUILD
- cup/README.md
- cup/cup.bzl
- cup/sample-project/BUILD
Macro that wraps a genrule to generate a Java parser from a CUP specification.
I don't think it's possible to use a Skylark rule, because cup reads from stdin.
> Add a genrule for cup

- WORKSPACE
- cup/BUILD
- jflex/BUILD
- third_party/BUILD
- third_party/deps.bzl
- third_party/org/apache/ant/BUILD
* Build JFlex with Bazel
- generate parser with the new cup macro (#442)
- generate scanner with public jflex rule
- build java lib
* add third/party/org/apache/ant
- also move `maven_import` of third_party dependencies in their own file
> Build JFlex (core) with Bazel

- scripts/deploy-source-code.sh
Replace the summary "Upgrade from JFLEX-SNPASHOT.jar"
by the initial commit message.
> Improve log message in aggregated-java-sources

- jflex/BUILD
- jflex/src/main/java/jflex/BUILD
- jflex/src/main/java/jflex/anttask/BUILD
- jflex/src/main/java/jflex/gui/BUILD
With this change
* //jflex is the core jflex library
* //jflex:jflex_bin adds the cli (jflex.Main), the gui and the ant task
> Split bazel build packages for gui, cli and anttask

- .cirrus.yml
because it exactly does `bazel info release`
> Minor cirrus: rename "check" task to "bazel_version"

- scripts/preparare-deploy-source-code.sh
The script fails in non $CI with
> git clone: Error jflex already exists
> git clone must be in directory "repo"

- .ci.bazelrc
The default is 67 (i.e. bazel uses 67% of host RAM) and I thinks that's fine. The reason no reason to reduce parallelism and use 10% only.
> Remove override of --ram_utilization_factor

- WORKSPACE
- third_party/unicode/BUILD
- third_party/unicode/LICENSE
- third_party/unicode/README.md
- third_party/unicode/unicode.bzl
Add the Unicode Character Definitions (UCD) for the versions JFlex supports.
Use http zip archive when it exists (version >4)
Use direct http file reference otherwise (version 1-3)
> Add BUILD targets for Unicode data

- third_party/unicode/BUILD
- third_party/unicode/unicode.bzl
Rename filegroup ucd_X to ucd_X_Y_Z.
Based on discussion for PR https://github.com/jflex-de/jflex/pull/526#issuecomment-433750425 Add old unicode versions.
> Add all deprecated Unicode major.minor versions

- .cirrus.yml
- WORKSPACE
- docs/BUILD
- docs/docs.bzl
- docs/manual_full.tex
* Update bazel-latex to 0.16
* Update bazel-pandoc to 0.2
* Fix Invalid toolchain
> external/bazel_pandoc/BUILD.bazel:6:1: in toolchain_type attribute of toolchain rule @bazel_pandoc//:pandoc_toolchain_linux: rule '@bazel_pandoc//:pandoc_toolchain_type' does not exist. Since this rule was created by the macro 'pandoc_toolchain', the error might have been caused by the macro implementation in /usr/local/google/home/regisd/.cache/bazel/_bazel_regisd/d1298cc00c93bfbf087444414b619b42/external/bazel_pandoc/toolchain.bzl:30:26
* Use package upquote instead of redefining \textquotesingle (now that it exists in bazel-latex)
* Remove output attribute unknown to bazel-pandoc (because it was only in my fork)
> Update padoc&latex to latest versions

- scripts/compile-aggregated-java-sources.sh
aggregated-java-sources fails to build with
> Using cached ant-1.7.0.jar
> lib/auto-value-annotations-1.6.2.jar
> Using cached auto-value-annotations-1.6.2.jar
> ./java/jflex/base/IntPair.java:12: error: package com.google.auto.value does not exist
> import com.google.auto.value.AutoValue;
>                             ^
> ./java/jflex/base/IntPair.java:22: error: cannot find symbol
> @AutoValue
> Fix Travis build

- .bazelrc
- .gitignore
- .travis.yml
- WORKSPACE
- cup-maven-plugin/pom.xml
- cup/pom.xml
- pom.xml
- scripts/compile-aggregated-java-sources.sh
- third_party/deps.bzl
* Fix #570. Build broken on Cirrus by upgrade to Bazel v1.0
* The `single_file` attribute has been replaced by `allow_single_file`.
Use **bazel_rules** v4 which fixed this. https://github.com/jflex-de/bazel_rules/pull/13
* add `--incompatible_depset_union=false`
bazel_pandoc https://github.com/ProdriveTechnologies/bazel-pandoc/issues/6 needs to update for incompatible_depset_union https://github.com/bazelbuild/bazel/issues/5817
* Use ProdriveTechnologies/bazel-latex#26 because `run_lualatex.py` is not executable
* In deps, use `https` rather than `http`
* Fix build broken on Travis due to upgrade to Xenial
* Use openjdk11 because whatever I ask for, that's what I get.
* Upgrade maven-compiler-plugin to 3.8.0 to fix _class file has wrong version 55.0, should be 53.0_
* Fix …
> Fix the build

- .travis.yml
Fix #573
Travis has changed the default VM to Xenial which cannot install java8.
> Use trusty for aggregated-java-sources

- .cirrus.yml
no-op, latest is 1.1.0, but this aligns with a CI best practice
> It is best practice to lock down aspects of your build container by specifying an additional tag to pin down the image in your configuration.
(from https://circleci.com/docs/2.0/circleci-images/#best-practices)
> Pin down bazel version 1.1.0

- jflex/src/main/cup/LexParse.cup
- jflex/src/main/java/jflex/core/Out.java
- jflex/src/main/java/jflex/core/ScannerException.java
- jflex/src/main/java/jflex/core/Skeleton.java
- jflex/src/main/java/jflex/generator/LexGenerator.java
- jflex/src/main/java/jflex/l10n/ErrorMessages.java
The ErrorMessages remains as the constant holder. But each constant should be a _single_ ErrorMessage(no s).
Also, define constant before methods, as per code-style compliance from PMD
> Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.
https://app.codacy.com/manual/regisd/jflex/file/39717832852/issues/source?bid=9096674&fileBranchId=9096674
> Introduce class ErrorMessages.ErrorMessage

- testsuite/testcases/src/test/cases/bol/bol-0.input
This partially reverts commit b3f1f036b888d6e3363dde0f03eeffcac95277df.
I accidentally moved the file out of `testsuite/testcases/src/test/cases`.
And the jflex-test-plugin use directory content to find tests (i.e. I accidentally completely removed the test with no test failure).
> Revert "Unit tests for BOL & EOL". Restore bol-0.input

- scripts/test-examples.sh
Replace `ant` by echo if the command is not available.
This disable ant on Travis, to work around sudden failure on Travis:
> scripts/test-examples.sh: line 44: ant: command not found
> The command "scripts/test-examples.sh" exited with 127.
https://travis-ci.org/jflex-de/jflex/jobs/616000480
> Disable ant build in test-examples.sh if command is missing

- java/jflex/migration/BUILD
- java/jflex/migration/BUILD.vm
- java/jflex/migration/Migrator.java
- java/jflex/migration/TestCase.java.vm
- java/jflex/testing/testsuite/golden/AbstractGoldenTest.java
- java/jflex/testing/testsuite/golden/BUILD
- java/jflex/testing/testsuite/golden/GoldenInOutFilePair.java
- java/jflex/velocity/Velocity.java
- javatests/jflex/testcase/caseless_jflex/BUILD
- javatests/jflex/testcase/caseless_jflex/CaselessGoldenTest.java
Improvements on #597 
* Order `data` before `deps` in `BUILD.vm` as required by bzl code style
* Improve logging of Migrator
* Refactor `TestCase.vm` to have one test method per golden, rather than looping over them all.
* Extract `AbstractGoldenTest` to improve code reuse
java/jflex/testing/testsuite/golden/AbstractGoldenTest.java
* Remove unused name in GoldenInOutFilePair
* Regenerate testcase/caseless accordingly
> Follow up on Migration tool

- java/jflex/testing/testsuite/BUILD
- java/jflex/testing/testsuite/JFlexTestRunner.java
- java/jflex/testing/testsuite/annotations/TestSpec.java
- javatests/jflex/testcase/arr_return/ArrReturnTest.java
- javatests/jflex/testcase/arr_return/BUILD
- javatests/jflex/testcase/arr_return/arr-flex.output
The legacy test suite allows to test the JFlex logs.
I don't know how useful it is (sounds like a _change test_ to me), but this change adds this feature to the `JflexTestRunner`.
> JflexTestRunner can now verify the output of JFlex itself

- scripts/test-java-format.sh
1. This files are generated code
2. They caus OOM errors, like
> java.lang.OutOfMemoryError: Java heap space
>	at com.google.common.collect.ImmutableList$Builder.<init>(ImmutableList.java:764)
>	at com.google.common.collect.ImmutableRangeMap$Builder.build(ImmutableRangeMap.java:146)
>	at com.google.googlejavaformat.java.JavaInput.<init>(JavaInput.java:285)
>	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:247)
>	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:234)
>	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:45)
>	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:26)
>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>	at …
> Do not run google-java-format on Unicode_x_y.java

- jflex/src/main/java/jflex/generator/Emitter.java
It seems relatively safe to emit ``zzScanError` as static.
> bazel-out/darwin-fastbuild/bin/jflex/LexScan.java:2213: warning: [MethodCanBeStatic] A private method that does not reference the enclosing instance can be static
>   private void zzScanError(int errorCode) {
>   ^
>     (see https://errorprone.info/bugpattern/MethodCanBeStatic)
>   Did you mean 'private static void zzScanError(int errorCode) {'?
> Make zzScanError static

- .bazelrc
- .ci.bazelrc
- WORKSPACE
- scripts/test-examples.sh
* https://github.com/ProdriveTechnologies/bazel-pandoc/issues/6 is fixed and we use bazel_pandoc-02 No need to work around with incompatiple_depset_union.
* test coverage aggregation worked locally, but never worked on CI. Forget about it. #608 uses partial reports
> Simplify .bazelrc

- scripts/preparare-deploy-source-code.sh
Follow-up fix of #613.
"oneline" and "fuller" are pretty aliases. "format:" is not what we want in this case.
> Fix of pseudo-format in aggregated-sources

- .bazelrc
https://errorprone.info/bugpattern/FieldMissingNullable
We don't have a nullness checker anyway.
This will reduce the size of the build logs.
> Disable error-prone FieldMissingNullable

- java/jflex/migration/TestCase.java.vm
- java/jflex/velocity/Velocity.java
WARNING: The directive.foreach.counter.initial.value property has been deprecated. It will be removed (along with $velocityCount itself) in Velocity 2.0.  Instead, please use $foreach.index to access the 0-based loop index and $foreach.count to access the 1-based loop counter.
> Update in Velocity engine directive.foreach.counter.initial.value

- javatests/jflex/testcase/large_input/LargeInputTest.java
- javatests/jflex/testcase/large_input/RepeatContentReader.java
Increase internal buffer size to 256kB in order improve performance.
Follow-up of #603
> Improve performance of RepeatedContentReader

- javatests/jflex/testcase/README.md
- testsuite/testcases/src/test/cases/encoding/README.md
Bazel doesn't allow to easily change the encoding of Java sources [ref](https://stackoverflow.com/a/43472003/94363).
And `—encoding` option applies to both source `.flex` and generated `.java`.
> Won't bazelify testcase/encoding

- javatests/jflex/testcase/large_input/BUILD
- javatests/jflex/testcase/large_input/LargeInputTest.java
- javatests/jflex/testcase/large_input/large_input.flex
Introduce a fakeRead() that changes `yychar` so that we can fakely jump to yychar just before Integer.MAX_VALUE and make the test run in a snap.
Follow-up of #603 and #605
> Make LargeInputTest run much faster by faking the scanner position

- .cirrus.yml
published 2019-12-03
https://blog.bazel.build/2019/11/20/bazel-1.2.0.html
> Upgrade to Bazel 1.2.1

- jflex/src/main/java/jflex/gui/MainFrame.java
The time it takes to run JFlex even on large specs is now small enough
to not need this button any more.
It is unlikely that the GUI is used much these days in any case.
> remove the MainFrame.stop button that called deprecated Thread.stop()

- jflex/src/main/java/jflex/generator/Emitter.java
This should remove warning from error-prone in generated code.
> generated getTokenName(int) (%cupdebug) can be static

- jflex/src/main/java/jflex/core/unicode/CharClasses.java
- jflex/src/test/java/jflex/chars/BUILD
- jflex/src/test/java/jflex/chars/IntervalGen.java
- jflex/src/test/java/jflex/core/unicode/BUILD
- jflex/src/test/java/jflex/core/unicode/IntCharSetGen.java
- jflex/src/test/java/jflex/core/unicode/IntCharSetQuickcheck.java
(continuing on #662)
* a few more IntCharSet quickcheck tests
* factor out the Interval generator so Intervals can be arguments to the test
> more IntCharSet quickcheck

- javatests/jflex/testcase/bol/BUILD
- javatests/jflex/testcase/bol/BolTest.java
- javatests/jflex/testcase/bol/State.java
- javatests/jflex/testcase/bol/bol.flex
- javatests/jflex/testcase/bol/bol2.flex
- jflex/src/main/cup/LexParse.cup
- testsuite/testcases/src/test/cases/bol/.gitignore
- testsuite/testcases/src/test/cases/bol/bol-0.output
- testsuite/testcases/src/test/cases/bol/bol-flex.output
- testsuite/testcases/src/test/cases/bol/bol.flex
- testsuite/testcases/src/test/cases/bol/bol2-0.input
- testsuite/testcases/src/test/cases/bol/bol2-0.output
- testsuite/testcases/src/test/cases/bol/bol2-flex.output
- testsuite/testcases/src/test/cases/bol/bol2.flex
- testsuite/testcases/src/test/cases/bol/bol2.test
the atBOL matching is done in the runtime engine on raw characters and doesn't go through the `cmap`, so we don't need to create classes for that case.
> do not create char classes for NL characters for atBOL matching

- java/jflex/testing/testsuite/JFlexTestRunner.java
- java/jflex/testing/testsuite/annotations/TestSpec.java
- javatests/jflex/testcase/arr_return/ArrReturnTest.java
- jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
- jflex/pom.xml
- jflex/src/main/java/jflex/Main.java
- jflex/src/main/java/jflex/anttask/JFlexTask.java
- jflex/src/main/java/jflex/core/DFA.java
- jflex/src/main/java/jflex/generator/BUILD
- jflex/src/main/java/jflex/generator/LexGenerator.java
- jflex/src/main/java/jflex/gui/GeneratorThread.java
Add assertion about the number of minimized DFA states.
See also #679
> Let Lex generator return the number of minimized states

- jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/ClassInfo.java
- jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
- jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/LexSimpleAnalyzerUtils.java
- jflex-maven-plugin/src/test/java/jflex/maven/plugin/jflex/LexSimpleAnalyzerUtilsTest.java
Hello,
Please consider for integration this patch for the jflex-maven-plugin to check also last-modified times for `%include` files in a JFlex file when possibly short-circuiting a rebuild. (It had been suggested in #217 that the jflex-maven-plugin supported this already, but I did not find that to be the case.)
Only `%include` files directly referenced by a `lexFile` would be checked by this patch and not any nested `%include` statements.
Thank you.
> Check %include files' modified times for rebuild too

- javatests/jflex/testcase/include/skeleton.nested
- javatests/jflex/testcase/include2/skeleton.nested
- jflex/src/main/java/jflex/base/Pair.java
- jflex/src/main/java/jflex/core/unicode/BUILD.bazel
- jflex/src/main/java/jflex/core/unicode/CMapBlock.java
- jflex/src/main/java/jflex/core/unicode/CharClassInterval.java
- jflex/src/main/java/jflex/core/unicode/CharClasses.java
- jflex/src/main/java/jflex/core/unicode/IntCharSet.java
- jflex/src/main/java/jflex/generator/CountEmitter.java
- jflex/src/main/java/jflex/generator/Emitter.java
- jflex/src/main/jflex/skeleton.nested
- jflex/src/main/jflex/skeleton.nested-1.8.0
- jflex/src/main/resources/jflex/skeleton.default
- jflex/src/test/java/jflex/core/unicode/BUILD.bazel
- jflex/src/test/java/jflex/core/unicode/CharClassesGen.java
- jflex/src/test/java/jflex/core/unicode/CharClassesQuickcheck.java
- testsuite/testcases/src/test/cases/include2/skeleton.nested
- testsuite/testcases/src/test/cases/spoon-feed-reader/fixed.skeleton.default
- testsuite/testcases/src/test/cases/spoon-feed-reader/problematic.skeleton.default
This addresses the memory issue #199. With more recent Unicode versions, the
character map took 0x110000 * 4 bytes, i.e. ~4MB. Most of this is never
accessed, but it still increases overall memory consumption esp for multiple
scanners.
This PR:
* changes the current one-level array to a two-level table structure
* adds quickcheck tests for the table construction
* updates runtime engine to use that structure
* updates skeleton files to remove reference to old ZZ_CMAP
* removes trailing white space in generated template code
Typical memory consumption for the char map decreases from ~4MB to < 100KB,
for simple scanners (little unicode use > 0xFF) to ~20KB.
Even though this increases the number of operations in the innermost loop,
with a bit of luck performance might actually benefit …
> memory performance: two-level cmap lookup

- pom.xml
Version 2.5 was fighting with google-java-format 1.7 on travis
> upgrade fmt-maven-plugin to version 2.9

- .travis.yml
- scripts/test-examples.sh
These should now build again, and cause test failure when they don't.
Also removed the cp to lib, which is now already done in the maven build to
make sure lib is always up-to-date.
> activate ant tests in examples

- jflex/src/main/java/jflex/core/unicode/CharClasses.java
- jflex/src/main/java/jflex/generator/Emitter.java
- jflex/src/test/java/jflex/core/unicode/CharClassesQuickcheck.java
* avoid one array access for the frequent case of input <= BLOCK_SIZE
* pre-compute the shift by BLOCK_SIZE
Current benchmark data is consistently faster (steady state and cold startup)
than 1.7.0 for inputs with characters <= 255.
> Optimise cmap access; now benchmarks better than 1.7.0

- javatests/jflex/testcase/include/IncludeGoldenTest.java
- javatests/jflex/testcase/include/skeleton.nested
- javatests/jflex/testcase/include2/skeleton.nested
- jflex/src/main/java/jflex/generator/Emitter.java
- jflex/src/main/jflex/skeleton.nested-1.8.0
- jflex/src/main/resources/jflex/skeleton.default
- jflex/src/test/java/jflex/chars/IntervalGen.java
- jflex/src/test/java/jflex/core/unicode/CharClassesGen.java
- jflex/src/test/java/jflex/core/unicode/IntCharSetGen.java
- testsuite/testcases/src/test/cases/include/skeleton.nested
- testsuite/testcases/src/test/cases/include2/skeleton.nested
- testsuite/testcases/src/test/cases/spoon-feed-reader/fixed.skeleton.default
- testsuite/testcases/src/test/cases/spoon-feed-reader/problematic.skeleton.default
* suppress "unused" warnings for generated yychar, yyline, etc (when actually unused)
* (includes skeleton sync with tests)
* address more error-prone warnings
> address more warnings

- jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
- pom.xml
I don't think JFlex uses any of the code in [CVE-2018-10237](https://github.com/advisories/GHSA-mvr2-9pj6-7w5j), but it's better to use the same version (26.0-jre) across the whole project anyway.
> bump guava version

- .ci.bazelrc
- .cirrus.yml
- java/jflex/util/javac/CompilerException.java
- javatests/jflex/testcase/apipirivate/ApiPrivateTest.java
- jflex/src/main/java/jflex/core/AbstractLexScan.java
- jflex/src/main/java/jflex/core/Macros.java
- jflex/src/test/java/jflex/state/StateSetQuickcheck.java
Bump from Bazel 2.1.0 to Bazel 3.5.0 (latest docker image)
Also fix
- https://errorprone.info/bugpattern/OverrideThrowableToString in CompilerException
- https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations in AbstractLexScan.java:376
- https://errorprone.info/bugpattern/ModifyCollectionInEnhancedForLoop in Macros.java:128
> Bump to Bazel 3.5.0

- .cirrus.yml
This avoid cloing the git repo and starting bazel again.
> Bazel build jflex_bin_deploy.jar in the main task

- java/jflex/ucd_generator/UcdScanner.java
- java/jflex/ucd_generator/model/PropertyValues.java
- java/jflex/ucd_generator/model/UnicodeData.java
- java/jflex/ucd_generator/scanner/AbstractPropertyValueAliasesScanner.java
- java/jflex/ucd_generator/scanner/ScriptExtensionsScanner.flex
- javatests/jflex/ucd_generator/UcdGeneratorIntegrationTest.java
With this change, the Unicode_6_3 is identical to the generation of the unicode-maven-plugin.
> UCD Generator: Normalize Script_Extensions values

- java/jflex/ucd_generator/UcdScanner.java
- java/jflex/ucd_generator/model/UnicodeData.java
- java/jflex/ucd_generator/util/PropertyNameNormalizer.java
- javatests/jflex/ucd_generator/UcdGeneratorIntegrationTest.java
In Unicode 6, Script_Extensions doens't have the alias "scx". However, in the implementation all properties are supposed to be self-aliased.
When we copy the Scrips to the Script_Extensions, also call `propertyNameNormalizer.putPropertyAlias("scriptextensions", "scriptextensions");`
Fixes a bug discovered thanks to #821
> Add missing "scriptextensions" self-alias

- java/de/jflex/ucd_generator/scanner/DerivedAgeScanner.java
- java/de/jflex/ucd_generator/scanner/UcdScanner.java
Follow-up of #831
Fixes workaround  #833
> DerivedAgeScanner shouldn't create intervals above maximumCodepoint

- java/de/jflex/ucd_generator/ucd/UnicodeData.java
Fixed in #837
Remove workaround for #833
Follow-up of #831
> addEnumPropertyInterval doesn't need hack for Unicode 2.1 anymore

- java/de/jflex/ucd_generator/emitter/unicode_properties/UnicodePropertiesEmitter.java
- java/de/jflex/ucd_generator/scanner/UcdScanner.java
- java/de/jflex/ucd_generator/ucd/UnicodeData.java
- javatests/de/jflex/ucd_generator/BUILD.bazel
- javatests/de/jflex/ucd_generator/TestedVersions.java
- javatests/de/jflex/ucd_generator/UcdGeneratorIntegrationTest.java
- javatests/de/jflex/ucd_generator/emitter/unicode_properties/UnicodeProperties.java.golden
- jflex/src/main/java/jflex/core/unicode/BUILD.bazel
Generate Unicode 1.1 with ucd_generator
* UnicodeData
* add compatibility intervals specific to Unicode 1.1. This is a port of the code in jflex-unicode-maven-plugin.
Contrary to the jflex-unicode-maven-plugin, this isn't done for later versions.
* add ucd_1_1 in gen_unicode_properties
* Adapt UcdScanner ; PropList and Blocks didn't exist in v1.1
* The integration test has a difficulty: the intervals returned by the Eclipse JDT parser are not in order.
* Rather than investigate, I just base the truth assertion on the content, without `inOrder()`.
* The source code can be verified in git to be identical, though. And I guess other tests would fail if we use the `alnum` properties in place of the `blank` properties.
* Remove the hardcoded v1.1.5 in UnicodeEmitter (which was a workaround …
> Generate Unicode 1.1 with ucd_generator

- jflex/src/main/java/jflex/core/unicode/UnicodeProperties.java
no-op change.
This file should not be modified manually, since it was generated by jflex-unicode-maven-plugin.
But it is is in preparation of #816 where the file is generated by ucd_generator (usign switch/case) and hence makes the git diff easier to review.
> Replace if statements by switch/case in UnicodeProperties

- WORKSPACE
https://github.com/jflex-de/bazel_rules/releases/tag/v1.8.2
> Upgrade jflex_bazel_rule to v1.8.2

- java/de/jflex/migration/BUILD.bazel
- java/de/jflex/migration/README.md
- java/de/jflex/ucd_generator/emitter/unicode_properties/UnicodePropertiesEmitter.java
- java/de/jflex/ucd_generator/emitter/unicode_version/UnicodeVersionEmitter.java
- java/de/jflex/velocity/Velocity.java
Add a method that takes a file, which saves the caller to create a stream from file.
Tested:
```
bazel run java/de/jflex/migration:migrator -- ~/Projects/jflex/testsuite/testcases/src/test/cases/syntaxnull
```
with 
which needed few adjsutments following #827
> Simplify velocity invocation with new render(..., File) method.

- java/de/jflex/testing/diff/BUILD.bazel
- java/de/jflex/testing/diff/DiffOutputStream.java
- java/de/jflex/testing/testsuite/JFlexTestRunner.java
By default, the DiffOutputStream throws a ComparisonFailure when content differs.
Allow to set a custom handler, so that a test can JFlexTestRunner print in System.err
This allows a more descriptive Error (instead of a generic ComparisonFailure)
> Improve error message in JFlexTestRunner

- .cirrus.yml
The code_coverage_tasks is killed by Cirrus with OOM.
* Increase memory from 5GB to 8GB
* Also increase cpu from 2 to 4
> Beef up the container for the bazel build.

- java/de/jflex/migration/unicodedatatest/testcaseless/UnicodeCaseless.flex.vm
- java/de/jflex/migration/unicodedatatest/testcaseless/UnicodeCaselessFlexGenerator.java
- java/de/jflex/migration/unicodedatatest/testcaseless/UnicodeCaselessTest.java.vm
Follow-up of #869 
The grammar was incorrectly trying to match \u10400 instead of \u010400
> Fix and re-enabled caseless test

- scripts/prepare-deploy-source-code.sh
[FATAL 12:32:32.066 src/main/cpp/blaze.cc:1289] Unknown startup option: '--remote_http_cache=http://127.0.0.1:12321'.
For more info, run 'bazel help startup_options'.
> Fix blaze option in prepare-deploy-source-code.sh

- .lgtm.yml
- pom.xml
Semmle LGTM analysis is currently broken with
> [autobuild] java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>     at java.lang.ClassLoader.defineClass1 (Native Method)
Probably following #909
This PR enables the profile on Java 11+, as required by the plugin.
> Disable fmt-maven-plugin plugin Below Java 11

- jflex/pom.xml
This makes it easier to work with VSCode etc. Should add a corresponding lifecycle mapping XML file to the CUP and jflex plugins later.
> jflex pom: add inline m2e lifecycle mapping

- cup-maven-plugin/pom.xml
- jflex-maven-plugin/pom.xml
- testsuite/jflex-testsuite-maven-plugin/pom.xml
> Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.
> pom: fix maven-shade-plugin errors

- java/de/jflex/testing/testsuite/JFlexTestRunner.java
- java/de/jflex/testing/testsuite/annotations/TestSpec.java
- jflex/src/main/java/jflex/core/AbstractLexScan.java
Simpler version of #880 without introducing log levels in the same go.
(not that log levels don't make sense, just should be separate)
> testsuite: sync verbosity behaviour with main jflex

- javatests/de/jflex/testcase/ccl_caseless/BUILD.bazel
- javatests/de/jflex/testcase/ccl_caseless/Ccl_caselessGoldenTest.java
- javatests/de/jflex/testcase/ccl_caseless/ccl_caseless-0.input
- javatests/de/jflex/testcase/ccl_caseless/ccl_caseless-0.output
- javatests/de/jflex/testcase/ccl_caseless/ccl_caseless.flex
- jflex/src/main/java/jflex/core/Macros.java
- jflex/src/main/java/jflex/core/NFA.java
- jflex/src/main/java/jflex/core/unicode/CharClasses.java
- jflex/src/test/java/jflex/dfa/DfaTest.java
- jflex/src/test/java/jflex/state/StateSetQuickcheck.java
In `%caseless` mode, char classes can contain characters that are not in the input char set, leading to an exception when we try to look up the class code for such a character.
- add a regression test case for this situation
- make CharClasses robust against this situation and ignores characters outside the input char set in NFA construction.
- minor warning reductions
Fixes #974
> make char classes robust against input char set size

- cup-maven-plugin/src/test/java/jflex/maven/plugin/cup/GenerateMojoTest.java
Replace `createTempDir()` with more secure `createTempDirectory()`.
It's just in testing code, but still nicer to avoid in general.
Fixes https://github.com/jflex-de/jflex/security/code-scanning/235
> cup-maven-plugin test: replace createTempDir()

- jflex/src/main/java/jflex/core/unicode/UnicodeProperties.java
Remove ArrayIndexOutOfBounds warning. We know the array has a length divisible by 2, so the access is not actually out of bounds. Comparing to `length - 1` instead of `length` makes the static analysis happy.
Should placate https://github.com/jflex-de/jflex/security/code-scanning/42
> jflex UnicodeProperties: remove warning

- jflex/src/main/java/jflex/anttask/JFlexTask.java
The super class implements Cloneable, so we should provide an implementation of the method, even if otherwise unused.
Fixes #991
> anttask: provide clone() implementation

- .github/workflows/build.yml
Always write back to the cache (the previous version never wrote back the cache, because the key always was a full hit).
> github: refine bazel cache management

- jflex/src/main/cup/LexParse.cup
- jflex/src/main/java/jflex/l10n/ErrorMessages.java
- jflex/src/main/java/jflex/logging/Out.java
- jflex/src/main/java/jflex/scanner/ScannerException.java
Shorter and less duplication. Our old Java hacks to get enums can finally be retired.
> jflex: make ErrorMessages a real enum

- docs/md/installing.md
- docs/md/lex-specs.md
- java/de/jflex/testing/testsuite/JFlexTestRunner.java
- jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
- jflex/src/main/cup/LexParse.cup
- jflex/src/main/java/jflex/Main.java
- jflex/src/main/java/jflex/anttask/JFlexTask.java
- jflex/src/main/java/jflex/core/Action.java
- jflex/src/main/java/jflex/core/OptionUtils.java
- jflex/src/main/java/jflex/generator/Emitter.java
- jflex/src/main/java/jflex/l10n/ErrorMessages.java
- jflex/src/main/java/jflex/logging/Out.java
- jflex/src/main/java/jflex/option/BUILD.bazel
- jflex/src/main/java/jflex/option/Options.java
- jflex/src/main/jflex/LexScan.flex
- jflex/src/main/resources/jflex/Messages.properties
- jflex/src/test/java/jflex/anttask/JFlexTaskTest.java
- jflex/src/test/java/jflex/core/unicode/IntCharGen.java
- jflex/src/test/java/jflex/core/unicode/IntCharSetGen.java
> generalise warning suppression

- jflex/src/main/java/jflex/generator/PackEmitter.java
(was introduced for debugging only and can lead to unwanted behaviour)
> jflex PackEmitter: remove debugging code

- .github/workflows/codeql.yml
Filter out unused-local-variable warnings for LexParse.java. Cup generates lots of unused local variables that we're not intending to eliminate.
> github: filter CodeQL results

- jflex/src/main/java/jflex/generator/Emitter.java
Make sure standalone/debug scanners actually close the input file. This doesn't matter much if called from the command line, but will leak resources if called from elsewhere.
This should eventually (after next release) fix <https://github.com/jflex-de/jflex/security/code-scanning/44>.
> jflex emitter: prevent resource leak

- pom.xml
- Hardcode an initial value for `<project.build.outputTimestamp>`
- Update maven plugins to version 3.2+
see https://maven.apache.org/guides/mini/guide-reproducible-builds.html
> Make maven build reproducible

- docs/md/installing.md
- docs/md/lex-specs.md
- javatests/de/jflex/testcase/six_digit_unicode_escape/failure2.out
- javatests/de/jflex/testcase/unicode_escape_warning/BUILD.bazel
- javatests/de/jflex/testcase/unicode_escape_warning/WarningsTest.java
- javatests/de/jflex/testcase/unicode_escape_warning/sys-out.txt
- javatests/de/jflex/testcase/unicode_escape_warning/warnings.flex
- jflex/src/main/java/jflex/core/AbstractLexScan.java
- jflex/src/main/java/jflex/l10n/ErrorMessages.java
- jflex/src/main/jflex/LexScan.flex
- jflex/src/main/resources/jflex/Messages.properties
`\u` with more than 4 or `\U` with more than 6 hex digits previously were silently split into the legal 4 or 6 unicode escape, followed by normal character matches. Usually these occurrences are errors, but there may be specifications that rely on this behaviour, so instead of an error we produce a warning that can be suppressed.
Fixes #183
> warn for unicode escapes that are too long

- docs/md/lex-specs.md
- javatests/de/jflex/testcase/ccl_bug/CclBugTest.java
- javatests/de/jflex/testcase/token_limit/BUILD.bazel
- javatests/de/jflex/testcase/token_limit/LimitTest0.java
- javatests/de/jflex/testcase/token_limit/LimitTest1.java
- javatests/de/jflex/testcase/token_limit/LimitTest2.java
- javatests/de/jflex/testcase/token_limit/LimitTest3.java
- javatests/de/jflex/testcase/token_limit/LimitTest4.java
- javatests/de/jflex/testcase/token_limit/LimitTest5.java
- javatests/de/jflex/testcase/token_limit/limit1.flex
- javatests/de/jflex/testcase/token_limit/limit2.flex
- javatests/de/jflex/testcase/token_limit/limit3.flex
- javatests/de/jflex/testcase/token_limit/limit4.flex
- javatests/de/jflex/testcase/token_limit/limit5.flex
- javatests/de/jflex/testcase/token_limit/limit_success.flex
- javatests/de/jflex/testcase/token_limit/sys-out1.txt
- javatests/de/jflex/testcase/token_limit/sys-out2.txt
- javatests/de/jflex/testcase/token_limit/sys-out3.txt
- javatests/de/jflex/testcase/token_limit/sys-out4.txt
- javatests/de/jflex/testcase/token_limit/sys-out5.txt
- jflex/lib/jflex-mode.el
- jflex/lib/jflex.vim
- jflex/src/main/java/jflex/core/AbstractLexScan.java
- jflex/src/main/java/jflex/generator/Emitter.java
- jflex/src/main/java/jflex/l10n/ErrorMessages.java
- jflex/src/main/jflex/LexScan.flex
- jflex/src/main/jflex/skeleton.nested
- jflex/src/main/resources/jflex/Messages.properties
- jflex/src/main/resources/jflex/skeleton.default
New directive
%token_size_limit <limit>
where `<limit>` is a Java number literal or qualified identifier provides an optional hard limit on token length.
The scanner buffer will not be increased beyond this length limit and if a longer token is encountered the scanner with throw an EOFException.
This is for applications that require memory limits when parsing untrusted input.
Implements https://github.com/jflex-de/jflex/issues/197
> implement optional limit on token size 

- benchmark/src/main/java/jflex/benchmark/JFlexBench.java
- jflex/src/main/java/jflex/generator/Emitter.java
- jflex/src/main/jflex/LexScan.flex
- jflex/src/main/jflex/skeleton.nested
- jflex/src/main/resources/jflex/skeleton.default
Benchmark results for MacOS, openjdk11:
```
JFlexBench.noActionLexer                                 10000        1    avgt    15  17.419 ±  0.152  ms/op
JFlexBench.noActionLexer                                 10000        2    avgt    15  17.370 ±  0.046  ms/op
JFlexBench.noActionPreLimit                              10000        1    avgt    15  17.513 ±  0.048  ms/op
JFlexBench.noActionPreLimit                              10000        2    avgt    15  17.531 ±  0.438  ms/op
JFlexBench.noActionLexer                                 10000        1  sample  8626  17.397 ±  0.012  ms/op
JFlexBench.noActionLexer:noActionLexer·p0.00             10000        1  sample        16.941           ms/op
JFlexBench.noActionLexer:noActionLexer·p0.50             10000        1  sample        17.334 …
```
> slight performance improvement for buffer limit

- .github/workflows/build.yml
The workflow is sometimes failing on jflex-maven-plugin not being available.
> github: make all plugins available for docs build

- .github/workflows/build.yml
Test JDKs 8, 11, and 17 by default. JDK 7 is no longer supported by JFlex.
> github: test more java lts versions

- docs/Makefile
- docs/citeproc-arg
But keep support for older versions, because CI uses pandoc 2.9, which still needs `--filter pandoc-citeproc`.
> docs: support newer pandoc versions that use `--citeproc`

- docs/md/installing.md
- docs/md/maven-plugin.md
- the examples/ refactor did not include docs update. Fix that.
- remove XML source highlighting, which mostly shows error colour, because it's not proper XML
> docs: update dir layout

- javatests/de/jflex/testcase/ccl_neg/BUILD.bazel
- javatests/de/jflex/testcase/ccl_neg/CCLNegTest.java
- javatests/de/jflex/testcase/ccl_neg/neg_overlap.flex
- jflex/src/main/java/jflex/chars/Interval.java
- jflex/src/main/java/jflex/core/RegExp.java
- jflex/src/main/java/jflex/core/unicode/CharClasses.java
In a negated character class that has overlapping content, such as `[^\n\s]`, the normalisation code is violating a precondition of `IntCharSet.sub()` and leaves the class content in an inconsistent state. This either triggers an exception at generation time if another set operation interacts with the inconsistent part, or may lead to matching wrong input at runtime if nothing else interacts with the set.
This PR fixes the problem by first computing the union of the class content `\n\s`, which becomes a single set (joining the overlapping parts) and then computing the complement of that set.
Fixes #1065
> Fix char class normalisation for overlapping class content

- RELEASE.md
- benchmark/pom.xml
- cup-maven-plugin/pom.xml
- benchmark module doesn't need to be deployed to Sonatype, it's mostly used when you're building from source anyway
- cup-maven-plugin only should be deployed when something (esp the version number) has changed
> skip deployment of some modules
