jflex-de/jflex

jflex-unicode-maven-plugin/src/main/java/jflex/DerivedAgeScanner.java
jflex-unicode-maven-plugin/src/main/java/jflex/JFlexUnicodeMojo.java
jflex-unicode-maven-plugin/src/main/java/jflex/NamedRange.java
jflex-unicode-maven-plugin/src/main/java/jflex/UnicodePropertiesSkeleton.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/CustomClassLoader.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/DiffStream.java

Found a few Maps being iterated twice while preparing another pull request. Then triggered a `mvn clean findbugs:findbugs findbugs:gui`, and fixed a few ones. No regressions found running `./run-test`

Fix FindBugs issues

---

jflex/src/main/jflex/skeleton.nested
jflex/src/main/resources/jflex/skeleton.default

make skeletons javadoc compliant

---

README.md
jflex/pom.xml
pom.xml

Remove antrun plugin

---

jflex/pom.xml
pom.xml

* Add version to fmt-maven-plugin.
* Use ${project.*} variables.

Fix maven warnings

---

scripts/run-tests.sh

Print version of java and javac before running tests

---

.travis.yml

Work around issue #281 
Close #281

Use oracledjdk8 rather than openjdk8

---

cup-maven-plugin/src/main/java/de/jflex/plugin/cup/CliCupInvoker.java
scripts/test-unit.sh

Before: Argument cannot be empty
After: Value for option -package cannot be empty

Improve error message when the CUP cli has incorrect arguments.

---

scripts/clean.sh
scripts/test-unit.sh

Fix failing finding local deleted artifacts
Follow-up of PR #297

Clean maven-metadata-local.xml 

---

pom.xml

Update ant to 1.7.0 -> 1.9.7

---

jflex/examples/cup-maven/pom.xml
jflex/examples/pom.xml

Fix POM description for cup-maven

---

jflex-maven-plugin/src/test/java/de/jflex/plugin/maven/JFlexMojoTest.java
jflex-maven-plugin/src/test/projects/recursion-test/src/main/jflex/org/jamwiki/parser/jflex/preprocessor.jflex
jflex-maven-plugin/src/test/projects/single-dir-test/src/main/jflex/preprocessor.jflex
jflex-maven-plugin/src/test/projects/single-file-test/src/main/jflex/preprocessor.jflex

Instead of org.jamwiki.parser.jflex

Minor: Move jamwiki test in org.jamwiki.parser

---

testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/JFlexTestsuiteMojo.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/TestCase.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/Tester.java

This is to disambiguate with jflex.Main

Minor: Rename jflextest.Main to jflextest.Tester

---

RELEASE.md

- Mention that merging should be done via pull request.

Minor: update RELEASE.md

---

scripts/deploy-source-code.sh

Calling this script has set my name to "Travis CI" :-/

Do not call git --global.config in deploy script

---

RELEASE.md

A few release documentation tweaks; added steps for website update.

Document website update

---

jflex/src/main/java/jflex/Emitter.java

adjust whitespace for character reporting

---

mvn-deploy.sh
pom.xml

Deployment

---

LICENSE.md

Correct my name in LICENSE file

Update Author name in LICENSE

---

scripts/deploy-source-code.sh

Add the inital commit that triggered the deploy-sources.sh script

Improve aggregated-java-sources log message

---

CODEOWNERS

This will:
- protect the cup directory
As a project admin, you can still commit. But the merge button is red.
https://help.github.com/articles/about-codeowners/
- help github in suggesting reviewers

Add owners file

---

mvn-deploy.sh
scripts/deploy-source-code.sh
scripts/mk-release.sh
scripts/run-tests.sh
scripts/test-java-format.sh

Based on https://app.codacy.com/app/regisd/jflex/files?#

Fix lint violations on *.sh

---

README.md

Update README: Add Bazel

---

jflex/src/main/java/jflex/Emitter.java
jflex/src/main/java/jflex/LexGenerator.java

* Add outputFileName field in Emitter
* Let `LexGenerator` return the generated file name for `emit()`.

Add outputFileName in Emitter

---

jflex/examples/cup-lcalc/README.md

Minor Update examples/cup-lcalc/README.md

---

jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/ClassInfo.java
jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/LexSimpleAnalyzer.java
jflex-maven-plugin/src/test/java/jflex/maven/plugin/jflex/ClassInfoTest.java
jflex-maven-plugin/src/test/java/jflex/maven/plugin/jflex/JFlexMojoTest.java
jflex-maven-plugin/src/test/java/jflex/maven/plugin/jflex/LexSimpleAnalyzerTest.java
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/DataFileType.java
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/DerivedAgeScanner.java
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/JFlexUnicodeMojo.java
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/NamedRange.java
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/NamedRangeSet.java
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/UnicodePropertiesSkeleton.java
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/UnicodeVersion.java
jflex-unicode-maven-plugin/src/main/jflex/ArchaicBlocksScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/ArchaicLineBreakScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/ArchaicPropListScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/BinaryPropertiesFileScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/EnumeratedPropertyFileScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/PropertyAliasesScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/PropertyValueAliasesScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/ScriptExtensionsScanner.flex
jflex-unicode-maven-plugin/src/main/jflex/UnicodeDataScanner.flex

- Move classes of **jflex-unicode-maven-plugin** in package `jflex.maven.plugin.unicode`
- Move classes of **jflex-maven-plugin** in `jflex.maven.plugin.jflex`

Move classes of maven plugins in jflex.maven.plugin

---

unrelated-sources.txt

Simplify the excluded files following 458

Simplify unreleated-sources

---

.travis.yml
compile.sh

Fix
```
$ java jflex.Main --version
Error: Could not find or load main class jflex.Main
```

Fix aggregated-java-sources execution

---

jflex/BUILD
jflex/src/main/cup/LexParse.cup
jflex/src/main/java/jflex/LexGenerator.java
jflex/src/main/java/jflex/Out.java
jflex/src/main/java/jflex/performance/BUILD
jflex/src/main/java/jflex/performance/Timer.java
jflex/src/main/jflex/LexScan.flex
jflex/src/test/resources/jflex/LexScan-test.flex
scripts/degraph/README.md
scripts/degraph/dep-graph.cfg

- Move java class in new package
- Add bazel package

Move class Timer in jflex.performance

---

.cirrus.yml

Split the build phases in Cirrus to make progress more visible

---

.bazelrc
testsuite/bzltestsuite/BUILD
testsuite/bzltestsuite/java/jflex/testing/JFlexTestRunner.java
testsuite/bzltestsuite/java/jflex/testing/annotations/NoExceptionThrown.java
testsuite/bzltestsuite/java/jflex/testing/annotations/TestSpec.java
testsuite/javatests/jflex/testcase/action_pipe/ActionPipeTest.java
testsuite/javatests/jflex/testcase/action_pipe/BUILD
testsuite/javatests/jflex/testcase/action_pipe/action-pipe.flex
testsuite/javatests/jflex/testcase/apipirivate/BUILD

bzltestsuite: Add assertThrows for jflex generation

---

testsuite/javatests/jflex/testcase/action_pipe/BUILD
testsuite/javatests/jflex/testcase/apipirivate/BUILD
testsuite/testsuite.bzl

Wrapper around java_test to make tests targets more concise.

Bazel macro jflex_testsuite

---

testsuite/bzltestsuite/README.md
testsuite/bzltestsuite/java/jflex/testing/BUILD
testsuite/bzltestsuite/java/jflex/testing/JFlexTestRunner.java
testsuite/bzltestsuite/java/jflex/testing/assertion/BUILD
testsuite/bzltestsuite/java/jflex/testing/assertion/MoreAsserts.java
testsuite/bzltestsuite/java/jflex/testing/assertion/ThrowingRunnable.java

Introduce an assert method to assert that a method throws something.
e.g.
```java
assertThrows("Dividing by zero is undefined in math",
ArithmeticException.class,
() -> {1/0};
}
```

MoreAssets.assertThrows()

---

.cirrus.yml

https://circleci.com/docs/2.0/caching/#source-caching

Save git repo in Cirrus cache

---

jflex/src/main/java/jflex/base/IntPair.java
jflex/src/main/java/jflex/core/AbstractLexScan.java
jflex/src/main/java/jflex/core/BUILD
jflex/src/main/java/jflex/core/LexGenerator.java
jflex/src/main/java/jflex/core/Macros.java
jflex/src/main/java/jflex/core/NFA.java
jflex/src/main/java/jflex/exceptions/MacroException.java
jflex/src/main/java/jflex/scanner/BUILD
jflex/src/main/java/jflex/scanner/LexicalStates.java

*  Move MacroException in jflex.exceptions
* Move IntPair in jflex.base
* Move LexicalStates in jflex.scanner

Move a few classes in their modules

---

scripts/compile-aggregated-java-sources.sh

Use wget to download deps rather than curl.
Copy compile.sh from aggregated-java-sources.sh It's easier to change deps on the master branch.
Also, introduce a function `mvnget` to download a maven dep.

Add compile-aggregate-sources.sh

---

jflex-maven-plugin/pom.xml

Remove duplicate dep on junit

---

jflex/src/main/java/jflex/core/NFA.java

Remove test which is always true.

Minor: simplify code

---

java/jflex/testing/diff/DiffOutputStream.java
javatests/jflex/testing/DiffOutputStreamTest.java

ArrayOutOfBoundException when actual is longer than expected.

Fix ArrayOutOfBoundException in DiffOutputStream

---

java/jflex/testing/diff/DiffOutputStream.java
javatests/jflex/testing/DiffOutputStreamTest.java

PMD doesn't like that a test has no assertion. This will allow to add assertThat(diffOutputStream.isCompleted()).isTrue();

Add new method DiffOutputStream.isCompleted()

---

docs/md/lex-specs.md
docs/pt_BR/manual-pt_BR.tex

fix byaccj typos in manual

---

.travis.yml

Remove Bazel build from Travis

---

README.md
docs/md/maven-plugin.md
jflex/examples/simple/README.md

Bump version number to 1.8.0 in documentation

---

jflex/src/main/java/jflex/generator/Emitter.java
jflex/src/main/java/jflex/generator/Emitters.java
jflex/src/main/java/jflex/generator/LexGenerator.java

add new constructor to Emitter class

add factory class for Emitter

---

jflex/pom.xml
pom.xml
scripts/compile-aggregated-java-sources.sh
third_party/com/google/auto_value/BUILD
third_party/deps.bzl

The current version wants annotations.jar on SDK9+
See https://github.com/google/auto/issues/503

Upgrade autovalue to v1.7

---

jflex/src/main/java/jflex/core/StateSet.java
jflex/src/main/java/jflex/core/StateSetEnumerator.java

documentation for StateSet and StateSetEnumerator

more code docs

---

.travis.yml
docs/xmanual.tex

Restore building docs in Travis

---

WORKSPACE

https://github.com/jflex-de/bazel_rules/releases/tag/v5

Upgrade Jflex bazel_rules to v5

---

WORKSPACE

The python issue ProdriveTechnologies/bazel-latex#23 has been fixed.

Use bazel_latex v0.19

---

WORKSPACE
scripts/test-bzl-format.sh

Error 
> WORKSPACE # reformat callsort
Reformat the WORKSPACE file ; I don't know how the presubmit tests passed.

Reformat WORKSPACE

---

.cirrus.yml
javatests/jflex/testcase/large_input/BUILD
javatests/jflex/testcase/large_input/LargeInputTest.java
javatests/jflex/testcase/large_input/RepeatContentReader.java
javatests/jflex/testcase/large_input/RepeatContentReaderTest.java
javatests/jflex/testcase/large_input/State.java
javatests/jflex/testcase/large_input/large_input.flex

Test that reproduces #536 (cannot process files of 2GB).
This test is based on a custom reader that generates content of any size.

Test Large input 2gb

---

javatests/jflex/ucd_generator/ucd/UcdVersionsTest.java
jflex/src/main/java/jflex/core/ScannerException.java
jflex/src/main/java/jflex/generator/Emitter.java

Minor change
https://pmd.github.io/latest/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname

Remove unnecessary fully qualified names

---

scripts/preparare-deploy-source-code.sh
scripts/test-examples.sh

Now the tilte contains the one-line description

Change format of pseudo commits

---

jflex/src/main/java/jflex/core/BUILD
jflex/src/main/java/jflex/core/Out.java
jflex/src/main/java/jflex/logging/BUILD
jflex/src/main/java/jflex/logging/StdOutWriter.java

Move StdOutWritter in new package logging.

Modularize logging

---

java/jflex/migration/Migrator.java
javatests/jflex/testcase/count/CountGoldenTest.java

Unfortunately #610 was followed by #617 
They both compiled individually, but not on top of each other.

Fix master build

---

.bazelproject

Simply  add the root directory.

Update .bazelproject for all directories

---

jflex/src/main/java/jflex/generator/Emitter.java
jflex/src/main/java/jflex/generator/LexGenerator.java
jflex/src/main/java/jflex/generator/PackEmitter.java

Make a few more methods static
https://errorprone.info/bugpattern/MethodCanBeStatic

Method can be static

---

javatests/jflex/testcase/ctorarg/BUILD
javatests/jflex/testcase/ctorarg/CtorBadArgTest.java

Unfortunate merge conflict because #623 was tested long before #601.

Fix import of ScannerException

---

docs/md/maven-plugin.md
jflex-maven-plugin/pom.xml
jflex-maven-plugin/src/site/site.xml
pom.xml

* Remove duplicate menu item _Goals_
* Review doc
* Disable javadoc report for the plugin

Update Maven site

---

jflex/src/main/java/jflex/core/NFA.java
jflex/src/test/java/jflex/generator/PackEmitterTest.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/CustomClassLoader.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/ExecUtils.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/LoadException.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestFailException.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestsuiteUtils.java

removing warnings, some dead code, and old debugging code.

minor code cleanup

---

jflex/src/main/java/jflex/core/CharClasses.java

use UnicodeProperties directly

decouple CharClasses from AbstractLexScan

---

jflex/src/main/java/jflex/chars/Interval.java
jflex/src/main/java/jflex/core/CharClasses.java
jflex/src/main/java/jflex/core/IntCharSet.java
jflex/src/main/java/jflex/core/Macros.java
jflex/src/main/java/jflex/core/NFA.java
jflex/src/main/java/jflex/core/RegExp.java
jflex/src/main/java/jflex/core/RegExp1.java
jflex/src/main/java/jflex/core/RegExp2.java
jflex/src/main/java/jflex/core/RegExps.java
jflex/src/main/java/jflex/exceptions/CharClassException.java
jflex/src/main/java/jflex/exceptions/MacroException.java
jflex/src/test/java/jflex/core/BUILD
jflex/src/test/java/jflex/core/IntCharSetTest.java

* Update javadoc and fix syntax
* Reformat code
* Small API change on Interval
* Remove `Internal.copy()` as there is already a copy constructor.
* Replace Interval copy ctor by static factory method `copyOf()` 
* Add new `Interval.ofCharacter()`
* Reduce field visibility
* Use Truth in IntCharSetTest

Minor code changes

---

jflex/examples/simple/src/main/java/Utility.java
jflex/src/main/cup/LexParse.cup
jflex/src/main/java/jflex/chars/Interval.java
jflex/src/main/java/jflex/core/CharClasses.java
jflex/src/main/java/jflex/core/IntCharSet.java
jflex/src/main/java/jflex/core/NFA.java
jflex/src/main/java/jflex/core/RegExp.java
jflex/src/main/java/jflex/core/unicode/UnicodeProperties.java
jflex/src/test/java/jflex/core/CharClassesTest.java
jflex/src/test/java/jflex/core/IntCharSetTest.java
jflex/src/test/java/jflex/core/RegExpTests.java

Follow-up of #656 
See _Effective java_, item 1.

Use Factory methods in Interval and IntCharSet

---

jflex/src/main/cup/LexParse.cup
jflex/src/main/java/jflex/Main.java
jflex/src/main/java/jflex/chars/Interval.java
jflex/src/main/java/jflex/core/CharClasses.java
jflex/src/main/java/jflex/core/IntCharSet.java
jflex/src/main/java/jflex/exceptions/GeneratorException.java
jflex/src/main/java/jflex/generator/LexGenerator.java

Currently for Interval and IntCharSet only, but would make sense for all set and partition implementations in JFlex.
This aim is to replace the horrible old printf debugging with contract and invariant checking over time.
This is separate from unit testing those implementations. The idea is that these assertions are for debugging only and will help find where exactly things have gone wrong.

simple invariant checking

---

jflex/src/main/java/jflex/chars/Interval.java
jflex/src/main/java/jflex/core/unicode/CharClasses.java
jflex/src/main/java/jflex/core/unicode/IntCharSet.java
jflex/src/main/java/jflex/state/StateSet.java
jflex/src/test/java/jflex/core/unicode/BUILD
jflex/src/test/java/jflex/core/unicode/CharClassesGen.java
jflex/src/test/java/jflex/core/unicode/CharClassesQuickcheck.java
jflex/src/test/java/jflex/core/unicode/IntCharSetQuickcheck.java
jflex/src/test/java/jflex/core/unicode/IntCharSetTest.java
jflex/src/test/java/jflex/state/BUILD
jflex/src/test/java/jflex/state/StateSetGen.java
jflex/src/test/java/jflex/state/StateSetQuickcheck.java
jflex/src/test/java/jflex/unicode/UnicodePropertiesTest.java

* more tested properties of IntCharSets
* added CharClasses
* added StateSet
* added counter-example shrinking to a few of the generators
* found a small bug in the tests in StateSet (fixed)
* refactor to remove `IntCharSet.getNext()`, tested for equivalence

more quickcheck tests

---

jflex/src/main/java/jflex/core/DFA.java
jflex/src/main/java/jflex/core/DfaFactory.java
jflex/src/main/java/jflex/core/NFA.java
jflex/src/main/java/jflex/generator/LexGenerator.java

This will remove a cyclic dep.

Extract NFA.getDfa() to DfaFactory.createFromNfa()

---

jflex/src/main/jflex/skeleton.nested
jflex/src/main/jflex/skeleton.nested-1.8.0
jflex/src/main/resources/jflex/skeleton.default

Provide @return and @throws javadoc in generated class

---

jflex/examples/cup-interpreter/src/main/java/Texp.java
jflex/src/main/java/jflex/generator/Emitter.java
jflex/src/main/jflex/skeleton.nested
jflex/src/main/jflex/skeleton.nested-1.8.0

replace all javadoc uses of <tt> with @{code }

---

cup-maven-plugin/pom.xml

version 1.0 is already released

bump cup-maven-plugin version

---

cup-maven-plugin/src/test/java/jflex/maven/plugin/cup/GenerateMojoIntegrationTest.java

(small copy/paste error in previous code)

cup-maven-plugin: test symbols file generation

---

RELEASE.md

We should be sure to have a green regression for everything before we
deploy and/or tag.

reorder release instructions

---

jflex/examples/cup-java/src/test/data/lexer-output.good
jflex/src/main/java/jflex/core/unicode/IntCharSet.java
testsuite/testcases/src/test/cases/java/README.md
testsuite/testcases/src/test/cases/java/java-1.input
testsuite/testcases/src/test/cases/java/java.test

* revert accidental change to test input
* revert assertion change (was intended to compare reference)

fix regression test

---

.github/workflows/build.yml
docs/Makefile
scripts/test-examples.sh

Progress on #767, testing out a few options for github workflows.

github workflows: basic build, unit tests, site

---

README.md

replace travis build badge with github badge

---

.github/workflows/build.yml
jflex/examples/cup-interpreter/pom.xml
jflex/examples/cup-java-minijava/pom.xml
jflex/examples/cup-java/pom.xml
jflex/examples/cup-lcalc/pom.xml
jflex/examples/simple/pom.xml
jflex/examples/standalone/pom.xml
jflex/examples/zero-reader/pom.xml
pom.xml

matrix build

---

testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestsuiteUtils.java

Initialize TestCase with Locale.US

---

.github/dependabot.yml

This should result in automatic updates of Maven deps
https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

Add Github Dependabot config

---

docs/BUILD.bazel
docs/manual_full.tex

* Use package verbatim
* Use font lm

Bazel manual.pdf use pacakges verbatim and lmodern

---

jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/UnicodeVersion.java

Accidental change from #812 and #674

Revert unwanted changes in jflex-unicode-maven-plugin

---

java/de/jflex/ucd_generator/emitter/unicode_properties/UnicodePropertiesEmitter.java
java/de/jflex/ucd_generator/scanner/UcdScanner.java
java/de/jflex/ucd_generator/ucd/PropertyValueIntervals.java
java/de/jflex/ucd_generator/ucd/UnicodeData.java
java/de/jflex/ucd_generator/ucd/Versions.java
javatests/de/jflex/ucd_generator/BUILD.bazel
javatests/de/jflex/ucd_generator/TestedVersions.java
javatests/de/jflex/ucd_generator/UcdGeneratorIntegrationTest.java
javatests/de/jflex/ucd_generator/emitter/unicode_properties/UnicodeProperties.java.golden
jflex/src/main/java/jflex/core/unicode/BUILD.bazel

Generate Unicode_2_0 with ucd_generator.

Generate Unicode_2_0 with ucd_generator

---

java/de/jflex/migration/testcase/Migrator.java
javatests/de/jflex/testcase/flex_syntax_error/BUILD.bazel
javatests/de/jflex/testcase/negation/BUILD.bzl
javatests/de/jflex/testcase/six_digit_unicode_escape/BUILD.bazel
javatests/de/jflex/testcase/spoon_feed_reader/BUILD.bazel

Folllow-up of previous changes #852 and #856

Cleanup Change

---

WORKSPACE

Update jflex_bazel_rule to retagged 1.8.2

---

java/de/jflex/migration/testcase/BUILD.vm
java/de/jflex/migration/testcase/Migrator.java
javatests/de/jflex/testcase/unicode_version_f/BUILD.bazel
javatests/de/jflex/testcase/unicode_version_f/UnicodeInvalidVersionTest.java
javatests/de/jflex/testcase/unicode_version_f/unicode-version-f.flex
javatests/de/jflex/testcase/unicode_version_f/unicode-version-f.output
testsuite/testcases/src/test/cases/unicode-version-f/unicode-version-f-flex.output
testsuite/testcases/src/test/cases/unicode-version-f/unicode-version-f.test

Migrate unicode-version-f to Bazel

Migrate Test unicode invalid version

---

jflex/pom.xml
jflex/src/main/java/jflex/dfa/BUILD.bazel
jflex/src/main/java/jflex/dfa/DFA.java
jflex/src/main/java/jflex/state/BUILD.bazel
jflex/src/main/java/jflex/state/StateSet.java
jflex/src/main/java/jflex/state/StateSetEnumerator.java
scripts/compile-aggregated-java-sources.sh
third_party/deps.bzl
third_party/javax/BUILD.bazel

Start nullness check verification on jflex/dfa and jflex/state

Enable nullness check on jflex/dfa and jflex/state

---

.github/workflows/gjf.yml

This makes it easier to be consistent between different CI systems and command line.

github: use existing scripts for code style action

---

cup-maven-plugin/src/main/java/jflex/maven/plugin/cup/GenerateMojo.java
java/de/jflex/ucd_generator/ucd/PropertyValueIntervals.java
jflex-maven-plugin/src/test/java/jflex/maven/plugin/jflex/JFlexMojoTest.java
jflex/src/main/java/jflex/core/AbstractLexScan.java
jflex/src/main/java/jflex/core/unicode/CharClasses.java
jflex/src/main/java/jflex/core/unicode/IntCharSet.java
pom.xml
scripts/test-java-format.sh

The previous version (2.12) does not work on JDK >= 16.

dependencies: upgrade fmt-maven-plugin to 2.19

---

cup-maven-plugin/README.md
cup-maven-plugin/pom.xml
cup-maven-plugin/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
jflex-maven-plugin/pom.xml
jflex-maven-plugin/resources/META-INF/m2e/lifecycle-mapping-metadata.xml

For jflex-maven-plugin and cup-maven-plugin (incl version bump for the latter)

add m2e lifecycle mapping to maven plugins

---

.github/workflows/build.yml
.github/workflows/gjf.yml

- new checkout action
- new setup-java action, now includes mvn cache

github: update workflow action versions

---

testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/DiffStream.java

Fixes https://github.com/jflex-de/jflex/security/code-scanning/43

maven-testsuite: remove potential Null deref

---

README.md

no real content updates, removed outdated Travis and Cirrus links

README: spelling, markdown lint

---

README.md

README: use markdown image links

---

benchmark/src/main/java/jflex/benchmark/JFlexBench.java
jflex/pom.xml
pom.xml

Code coverage now generated via bazel

Remove jacoco

---

jflex/lib/jflex-mode.el
jflex/lib/jflex.vim

lib: syntax highlighting for new directives

---

.github/workflows/codeql.yml
jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
jflex/src/main/java/jflex/core/RegExps.java
jflex/src/main/java/jflex/core/unicode/IntCharSet.java
jflex/src/main/jflex/LexScan.flex
jflex/src/test/java/jflex/core/RegExpTest.java
scripts/run-tests.sh
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/CustomClassLoader.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/InputOutput.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/JFlexTestsuiteMojo.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestCase.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestResult.java
testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestsuiteUtils.java

- suppress warnings in generated code
- annotate the rest

fix @Override annotation warnings

---

pom.xml
third_party/deps.bzl
third_party/maven_install.json

dependencies: update guava to 31.1-jre

---

javatests/de/jflex/testcase/no_warn/BUILD.bazel
javatests/de/jflex/testcase/no_warn/NoWarnTest1.java
javatests/de/jflex/testcase/no_warn/NoWarnTest2.java
javatests/de/jflex/testcase/no_warn/NoWarnTest3.java
javatests/de/jflex/testcase/no_warn/no_warn1.flex
javatests/de/jflex/testcase/no_warn/no_warn1_sysout.txt
javatests/de/jflex/testcase/no_warn/no_warn2.flex
javatests/de/jflex/testcase/no_warn/no_warn3.flex
jflex/src/main/java/jflex/core/OptionUtils.java

tests: warn/no-warn/suppress, fix %warn all

---

.github/workflows/build.yml
cup-maven-plugin/src/main/java/jflex/maven/plugin/cup/JavaUtils.java
java/de/jflex/ucd_generator/emitter/unicode_properties/UnicodeProperties.java.vm
javatests/de/jflex/ucd_generator/emitter/unicode_properties/UnicodeProperties.java.golden
jflex/src/main/java/jflex/core/Action.java
jflex/src/main/java/jflex/core/unicode/UnicodeProperties.java
jflex/src/main/java/jflex/generator/CountEmitter.java
jflex/src/main/java/jflex/gui/GridPanel.java
pom.xml

Just builds all javadoc, no further validation. doclint has too many errors for CI still.
Implements #729 (without doclint)

github: add javadoc job

---

cup-maven-plugin/src/main/java/jflex/maven/plugin/cup/GenerateMojo.java

cup-maven-plugin: fix comment typos

---

RELEASE.md
jflex/changelog.md
scripts/README.md
scripts/mvn-install-fastbuild.sh
scripts/prepare-deploy-source-code.sh
scripts/test-java-format.sh
scripts/test-unit.sh

Add notable issues from [milestone 1.9.0](https://github.com/jflex-de/jflex/milestone/17).
No set release date yet.

update change log for JFlex 1.9.0

---

RELEASE.md
docs/Makefile
docs/md/ant-task.md
docs/md/installing.md

- add checklist to RELEASE.md
- update release date
- clean up latex build

1.9.1 release items for manual
